### ISSUE TITLE
Integer format

### ISSUE THREAD

**Issue by serprex** [L3viathan/OIL#4]
Currently if a user inputs '0053' then it'll be treated as if they input '53'

Ideally if a user inputs '0053' into an echo program, it'll print '0053'

I'd like to suggest two potential solutions:
1. All cells are strings, & we only interpret those cells as integers for 'integer operations'. This would then need to specify the format for things like '-00000'
2. Each integer has a unique string representation, '0053' & '-000' are not integers

oilrs would prefer the latter. It's simpler & makes it easy to force those unique mappings to always be stored as integers vs strings

**Comment by L3viathan** [comment]
I consider this a bug in my implementation; an input of '0053' should result in the string '0053'.

Therefore, I choose solution 2. An integer is any string that matches `^(0|-?[1-9]\d*)$`.
