### ISSUE TITLE
Command addition thread

### ISSUE THREAD

**Issue by L3viathan** [L3viathan/OIL#5]
This is the thread for new potential commands that can be added to future versions of OIL.

I'm very conservative regarding the addition of commands, but not completely opposed, if their usefulness can be demonstrated, and they are primitive enough. If while programming in OIL you find that you're missing a certain feature, this is the place to suggest them.

Any new commands will make OIL slightly backwards-incompatible (because previously nopping operations suddenly have a different effect), and this should be kept in mind.

A few potential commands come to my mind:

- **Random number**: This would very obviously be useful, but it is also one of the potential commands that might be too complex. The random number would need to be bound in some way, whether through a default range (say, 0-99, or even 0-1) or through one or two arguments. Alternatively, I could also imagine a random jump (similar to the existing conditional jump; jump to either of two given cells, randomly). At the moment I'm leaning slightly towards including this at some point.

- **Flip sign**: The sign of a given cell is flipped in-place: 4 becomes -4, -3 becomes 3, 0 stays 0, and "foo" becomes 0. This would have the second usecase of forcing a string to become a number, although this is easily done now with incrementing and then decrementing. This is a frequently needed operation, on the other hand, it is also one that is trivially implemented without a designated command. At the moment I'm leaning towards rejecting this.

- **chr/ord**: Two potential commands that would come as a pair: Convert a number into the character that has the number as a unicode codepoint, and convert a character into the number of its unicode codepoint. This would introduce functionality that is impossible to do in OIL 2.1, and would be very useful, but there are many open questions: What happens with strings that are longer than one character? What happens with numbers that don't correspond to a unicode character? Without these questions addressed, this won't be included.

**Comment by serprex** [comment]
Random number: replace target cell with a value of 0..cell-value. Not sure if upper bound should be inclusive or excluive tho

ord/chr: Could make it in the vein of explode/implode. So string explodes into a list of unicode values, numberes implode into string. Invalid unicode maps to '\uFFFD'

On backwards incompatibility: perhaps make it illegal to execute invalid instructions. ie program aborts with error message

**Comment by L3viathan** [comment]
**Random number:** In that case definitely inclusive, as `random` `cell` `1` should set the cell to either 0 or 1 then.

**ord/chr:** That sounds reasonable.

**Backwards incompatibility:** There's not a big enough userbase of OIL that would make backwards incompatibility too tragic; and I'm pretty sure every script I've written will work even if we add a couple of commands. What will definitely not happen is any error messages, that goes against the spirit of OIL. Exiting would be possible, but I don't think it's necessary. I guess interpreters could implement some kind of strict mode (à la perl's `use strict;`) that would warn or exit in this case for debugging, but it shouldn't be the default.
