### ISSUE TITLE
Remove concept of 'empty cell' from spec

### ISSUE THREAD

**Issue by serprex** [L3viathan/OIL#8]
Idea: default cell value is empty string, executing empty string exits program

Alternatively let 3 be the sole halting mechanism

This raises the other question: it seems odd that 0 is the default cell value, as opposed to empty string

PS the third parameter of 10 seems superfluous, why not fallthrough?

**Comment by L3viathan** [comment]
In short: I won't remove the concept of an unassigned cell.

**let 3 be the sole halting mechanism** — No, I want programs to exit when they run into nothingness.

I'll think about having empty strings be the default cell. How would that help? I would have to check if changing that would break anything.

I don't want programs to exit in general when an empty string is executed, only when it's an unassigned cell.

**Comment by serprex** [comment]
Not sure it would help, only makes the values similar to if one were to leave trailing newlines at end of file, though with empty-cell being a thing, that isn't the case. It'd also support implementing assigning an empty string as a delete operation on the cell.. except that's still on the concept of removing unassigned

It'd also toss out the current difference between oilrs & OIL where reads initialize cells for OIL but not for oilrs

Closing as this clarifies stance of empty cells
