### ISSUE TITLE
Move stdlib to its own repo

### ISSUE THREAD

**Issue by serprex** [L3viathan/OIL#9]
I'd like [oilrs](https://github.com/serprex/oilrs) to reuse the stdlib by having it as a submodule

Of course this also assumes that the stdlib in this repository falls under a free-to-use-however license

**Comment by L3viathan** [comment]
Sounds good, I'll move it to a separate repository later today.

Maybe it would indeed be good to put a license on both repositories, which would of course be very liberal (I guess MIT/BSD).

**Comment by L3viathan** [comment]
I've moved the stdlib to [this repository](https://github.com/L3viathan/oil-stdlib), and added a license to both repos (both MIT).
